### PR TITLE
PXP-419: [Wukong CLI] Cursor disappear when terminating the interactive session in the middle.

### PR DESCRIPTION
**Pull request by jk-gan**
## Summary

Ticket: [PXP-419](https://mindvalley.atlassian.net/browse/PXP-419)

### Fixed
- [x] make sure the cursor will not be hidden after user press `ctrl + c` during selections prompt

### CODE REVIEW

**Comment by sauron-droid** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/39#" title="Author self-approved">jk-gan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by onimsha — COMMENTED** [review]
I got this in the debug build 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Interrupted, error: "read interrupted" }', src/commands/deployment/execute.rs:233:22
```

Should we let the application panic ? Since this is intentional, can we handle the signal and exit the application properly ?

**Comment by jk-gan** [comment]
ya that make sense in debug build, because `ctrl + c` will terminate the current session so the selection prompt will throw error. It wouldn't show on release build.

**Comment by jk-gan** [comment]
I can try to handle this panic

**Comment by jk-gan** [comment]
I've handled the panic.

**Comment by sauron-droid** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/39#" title="Author self-approved">jk-gan</a>*, *<a href="https://github.com/mindvalley/wukong-cli/pull/39#issuecomment-1306743507" title="Approved">onimsha</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by onimsha — APPROVED** [review]

**Comment by sauron-droid** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/39#" title="Author self-approved">jk-gan</a>*, *<a href="https://github.com/mindvalley/wukong-cli/pull/39#pullrequestreview-1171545787" title="Approved">onimsha</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
