### PR TITLE
PXP-463: [CLI] Implement the rollback command

### PR DESCRIPTION
**Pull request by jk-gan**
## Summary

This PR add a `wukong deployment rollback` command to rollback to the previous deployment.

Ticket: [PXP-463](https://mindvalley.atlassian.net/browse/PXP-463)

### Added
- [x] add `wukong deployment rollback`

[PXP-463]: https://mindvalley.atlassian.net/browse/PXP-463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by sauron-droid** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/57#" title="Author self-approved">jk-gan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by onimsha** [comment]
Test with `deployment execute` command yields the following error 

```
❯ ./target/debug/wukong deployment execute
Not detecting any flags, entering deployment terminal......
Current application: mv-wukong-ci-mock
✔ Step 1: Please choose the namespace you want to deploy · Prod
You've selected `Prod` as the deployment namespace.

✔ Step 2: Please choose the version you want to deploy · Green
You've selected `Green` as the deployment version.

✔ Step 3: Please choose the build artifact you want to deploy · v0.0.3-build-1
You've selected `v0.0.3-build-1` as the build artifact for this deployment.

Error - API Response Error: <query>:3:3: In argument "buildNumber": Expected type "Int!", found null.
```
cc @Fadhil

**Comment by onimsha** [comment]
> Test with `deployment execute` command yields the following error
> 
> ```
> ❯ ./target/debug/wukong deployment execute
> Not detecting any flags, entering deployment terminal......
> Current application: mv-wukong-ci-mock
> ✔ Step 1: Please choose the namespace you want to deploy · Prod
> You've selected `Prod` as the deployment namespace.
> 
> ✔ Step 2: Please choose the version you want to deploy · Green
> You've selected `Green` as the deployment version.
> 
> ✔ Step 3: Please choose the build artifact you want to deploy · v0.0.3-build-1
> You've selected `v0.0.3-build-1` as the build artifact for this deployment.
> 
> Error - API Response Error: <query>:3:3: In argument "buildNumber": Expected type "Int!", found null.
> ```
> 
> cc @Fadhil

Trace log from Wukong CLI shows that it fails on the CHANGELOG generator part 

```
✔ Step 3: Please choose the build artifact you want to deploy · v0.0.3-build-1
You've selected `v0.0.3-build-1` as the build artifact for this deployment.

⠁ Generating changelog ...                                                                                                                                                        Debug - request: RequestBuilder { method: POST, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(4000), path: "/api", query: None, fragment: None }, headers: {"content-type": "application/json"} }
Debug - graphQL query:
query ChangelogsQuery($application: String!, $namespace: String!, $version:
String!, $buildArtifactName: String!) {
  changelogs(application: $application, namespace: $namespace, version:
  $version, buildArtifactName: $buildArtifactName) {
    author
    messageHeadline
    shortHash
    url
  }
}

⠉ Generating changelog ...                                                                                                                                                        Trace - signal: Want
Trace - signal: Want
Trace - poll_want: taker wants!
Trace - signal: Want
Trace - deregistering event source from poller
Trace - signal: Closed
Error - API Response Error: <query>:3:3: In argument "buildNumber": Expected type "Int!", found null.
```

**Review by onimsha — APPROVED** [review]

**Comment by sauron-droid** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/57#" title="Author self-approved">jk-gan</a>*, *<a href="https://github.com/mindvalley/wukong-cli/pull/57#pullrequestreview-1296878097" title="Approved">onimsha</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
