### PR TITLE
PXP-516: [CLI] Fix multiple annotations support 

### PR DESCRIPTION
**Pull request by mfauzaan**
## Summary
This PR fixes an issue where only one secret is displayed when multiple annotations are passed in the same config file due to the use of a hashmap to store the data. To address this issue, we've changed the hashmap to a vector to store and display multiple datasets.

Ticket: [PXP-516](https://mindvalley.atlassian.net/browse/PXP-516)

## What's Changed

- [x] Replaced the hashmap with a vector in the annotation config to store multiple datasets.
- [x] Updated the display logic to handle multiple datasets.

[PXP-515]: https://mindvalley.atlassian.net/browse/PXP-515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PXP-514]: https://mindvalley.atlassian.net/browse/PXP-514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PXP-516]: https://mindvalley.atlassian.net/browse/PXP-516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by sauron-droid** [comment]
PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by jk-gan — CHANGES_REQUESTED** [review]
LGTM, but I don't like the error message of this. I was testing multiple annotations in one file, and the error doesn't show me which annotation is invalid, only show me the config file name.

Screenshot 2023-04-14 at 4 07 30 PM

**Review by jk-gan — APPROVED** [review]
LGTM

**Comment by sauron-droid** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/88#pullrequestreview-1385032788" title="Approved">jk-gan</a>*, *<a href="https://github.com/mindvalley/wukong-cli/pull/88#" title="Author self-approved">mfauzaan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
