### PR TITLE
PXP-514: [CLI] Rename 'dev config-synthesizer' to 'dev config pull'

### PR DESCRIPTION
**Pull request by mfauzaan**
## Summary
With the latest spec update in [RFC07](https://mindvalley.atlassian.net/wiki/spaces/PXP/pages/560398337/RFC07+-+Command+Specs+-+Dev#Dev-Config), the dev `config-synthesizer` command has been renamed to `dev config pull` to fit within the new dev config command group. This PR updates the codebase to reflect this change.

### Usage

To use the command, simply run: `wukong dev config pull {path}`

Ticket: [PXP-514](https://mindvalley.atlassian.net/browse/PXP-514)
Intial PR: [PR-80](https://github.com/mindvalley/wukong-cli/pull/80)

## What's Changed

- [x] Renamed `dev/config-synthesizer.rs` command file to `dev/config/pull.rs`
- [x] Moved command group of this command from `DevSubcommand` to `ConfigSubcommand`
- [x] Updated test case to match the new command name and group

[PXP-515]: https://mindvalley.atlassian.net/browse/PXP-515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PXP-514]: https://mindvalley.atlassian.net/browse/PXP-514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by sauron-droid** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/87#" title="Author self-approved">mfauzaan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by onimsha — APPROVED** [review]

**Comment by sauron-droid** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/87#" title="Author self-approved">mfauzaan</a>*, *<a href="https://github.com/mindvalley/wukong-cli/pull/87#pullrequestreview-1384472667" title="Approved">onimsha</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by jk-gan — APPROVED** [review]
LGTM

**Comment by sauron-droid** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/87#pullrequestreview-1384777089" title="Approved">jk-gan</a>*, *<a href="https://github.com/mindvalley/wukong-cli/pull/87#" title="Author self-approved">mfauzaan</a>*, *<a href="https://github.com/mindvalley/wukong-cli/pull/87#pullrequestreview-1384472667" title="Approved">onimsha</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
