### PR TITLE
PXP-567: [CLI] Crash when entering interactive session too long

### PR DESCRIPTION
**Pull request by jk-gan**
## Summary

This issue occur because we only check the token expiry when the cli start, so if the user stay in the interactive session, the token might be expired when we are calling API. This PR will check the token expiry before every api calls. 

Sidenote: Some of the codes actually come from v2.0 refactoring, such as the `Config` and `QueryClient`, as I think the new design is suitable for this fix

Ticket: [PXP-567](https://mindvalley.atlassian.net/browse/PXP-567)

### Changed
- [x] Check token expiry on every api calls 

[PXP-567]: https://mindvalley.atlassian.net/browse/PXP-567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by sauron-droid** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/119#" title="Author self-approved">jk-gan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by sauron-droid** [comment]
PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by onimsha** [comment]
@jk-gan still get the error

image

**Comment by jk-gan** [comment]
> @jk-gan still get the error
> image

Checking right now

**Comment by jk-gan** [comment]
@onimsha this should be fixed, I'm doing testing right now (waiting the token to be expired

**Review by onimsha — APPROVED** [review]

**Comment by sauron-droid** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/119#" title="Author self-approved">jk-gan</a>*, *<a href="https://github.com/mindvalley/wukong-cli/pull/119#pullrequestreview-1529843269" title="Approved">onimsha</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
