### PR TITLE
PXP-416: [Wukong CLI] Allowing to override the api_url and okta_client_id in the config

### PR DESCRIPTION
**Pull request by jk-gan**
## Summary

Ticket: [PXP-416](https://mindvalley.atlassian.net/browse/PXP-416)

### Added
- [x] **BREAKING**: add `wukong_api_url` and `okta_client_id` into config file
Screenshot 2022-11-03 at 4 22 54 PM

User will get the message if they updated to this version but using the old `config.toml` values:
Screenshot 2022-11-03 at 5 03 48 PM

They have to remove the existing `config.toml` file and run `wukong init` to re-initialise the config then it should be all good.

- [x] add a way to get and set `wukong_api_url` and `okta_client_id` by using `wukong config get/set wukong-api-url` and `wukong config get/set okta-client-id` respectively
Screenshot 2022-11-03 at 5 18 05 PM

Screenshot 2022-11-03 at 5 17 33 PM

### Changed
- [x] add a new feature flag `prod` to set the prod values as default values to the config file, it is used in production build in github actions
    - `cargo run --features prod -- command` will use the prod values

### Fixed
- [x] fix a bug when the user re-init wukong-cli using `wukong init` command, the config file is not creating a new config

### CODE REVIEW

**Comment by onimsha** [comment]
@jk-gan does this mean for older clients, after upgrading to new version containing this changes, has to re-issue the `wukong init` command once ?

**Comment by jk-gan** [comment]
> @jk-gan does this mean for older clients, after upgrading to new version containing this changes, has to re-issue the `wukong init` command once ?

yup, I just updated the description to show what the user will see and what should they do

**Review by onimsha — COMMENTED** [review]
I don't see the part of using environment variable to override these configs, are implementing it in this PR ?

**Comment by jk-gan** [comment]
isn't we want to change to use config file instead?

**Comment by onimsha** [comment]
> isn't we want to change to use config file instead?

Ah, since the original ticket was also asking to use the environment variable. But yeah i guess we better to use the `wukong config set` to provide consistency when changing Wukong's config. I'll update the ticket .

**Comment by jk-gan** [comment]
I'm changing a better error message to show the full path of the `config.toml` file so they can just run `rm /path/to/config.toml` to remove it

**Comment by onimsha** [comment]
> I'm changing to a better error message to show the full path of the `config.toml` file so they can just run `rm /path/to/config.toml` to remove it

Must they delete the config ? will running `wukong init` on top of the current config will overwrite the config itself ?

**Comment by jk-gan** [comment]
For the current flow, they have to delete the config manually, the `wukong init` will have to ask the user if they want to use the existing logged in account, and that requires the CLI to read the `config.toml` file in order to know whether there the user currently logged in or not, but since the `config.toml` file don't have `wukong_api_url` and `okta_client_id` field (because they are required fields, not optional fields), the CLI will keep returning the Bad TOML data error.

**Comment by jk-gan** [comment]
updated the error suggestion

**Review by onimsha — APPROVED** [review]

**Pull request merged**
