### PR TITLE
PXP-670: [CLI] Implement the AppSignal integration to the deployment status command

### PR DESCRIPTION
**Pull request by jk-gan**
## Summary

Screenshot 2024-02-28 at 3 44 46 PM

The PR also include the error handling when the application config is not enabled or when the appsignal integration is not enabled.
Screenshot 2024-02-28 at 3 45 12 PM
Screenshot 2024-02-28 at 3 44 59 PM

Ticket: [PXP-670](https://mindvalley.atlassian.net/browse/PXP-670)

### Added
- [x] add `wukong deployment status` command 

### Fixed
- [x] fix the error handling for application config file
- [x] all the test cases are using the application config file 

### Changed
- [x] most of the commands now only work in the directory that contains `.wukong.toml` file  

[PXP-670]: https://mindvalley.atlassian.net/browse/PXP-670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by sauron-droid** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/198#" title="Author self-approved">jk-gan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by onimsha** [comment]
@jk-gan I got this error while trying to test the feature

image

I understand this PR does not cover the init logic, but I wonder how did you test it ?

**Comment by onimsha** [comment]
> @jk-gan I got this error while trying to test the feature
> 
> image
> 
> I understand this PR does not cover the init logic, but I wonder how did you test it ?

I know how to get past this error. Now I got this 

image

**Review by onimsha — COMMENTED** [review]
There are two major takeaways from this PR:

* The CLI is still expecting the config `application_name` in the global config. We will need to modify it to use the application config exclusively.
* The CLI is possibly giving wrong data from AppSignal. The output is not matching with the mockup and the magic link is pointing to some `Unknown deployment` in AppSignal.

We will need to fix these issues before merging this PR.

**Comment by jk-gan** [comment]
AppSignal doesn't recognize the latest deploy marker from the url param, so I will use `incident_marker=last` for the link

**Comment by onimsha** [comment]
@jk-gan can you match the actual UI with the mockup as closet possible ? At least I want to see the `APM` as table title. 

For the `Prod`, I think we can just show the name of the AppSignal Environment ? It will be clearer to developer about where we're pulling data from. 

image

**Review by onimsha — APPROVED** [review]

**Comment by sauron-droid** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/198#" title="Author self-approved">jk-gan</a>*, *<a href="https://github.com/mindvalley/wukong-cli/pull/198#pullrequestreview-1923945098" title="Approved">onimsha</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
